const MESSAGES = {
  SCHEDULE_CLIPBOARD_CLEAR: 'SCHEDULE_CLIPBOARD_CLEAR',
  CLEAR_CLIPBOARD_NOW: 'CLEAR_CLIPBOARD_NOW'
}

const ALARMS = {
  CLEAR_CLIPBOARD: 'CLEAR_CLIPBOARD'
}

export { MESSAGES, ALARMS }
