name: Lint check

on:
  push:
    branches: [ main, dev ]
  pull_request_target:
    branches: [ main, dev ]

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: '@tetherto'

      - name: Install worker dependencies
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf ssh://
          git config --global url."https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          npm install --install-links --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Run ESLint
        run: npm run lint
